sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")

fix: I used the correct port for Mamp which I'm using

sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'rooted'@'localhost' (using password: YES)")

fix: I used the user: root. 